### ISSUE TITLE
datamodel-code-generator does not allow additional properties with `additionalProperties: { type: string }` 

### ISSUE THREAD

**Issue by aucampia** [aucampia/issues#2]
https://github.com/koxudaxi/datamodel-code-generator

```yaml
  EventStreamTableTags:
    title: Tags
    description: |
      Ad-hoc user defined metadata. These should have no impact on the resource
      behavior. See
      <https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/tag-resources?tabs=json>.
    type: object
    additionalProperties: true
    properties:
      owner:
        description: |
          A URI identifying the team that this resource belongs to.
        type: string
      description:
        description: |
          A description of the event stream table.
        type: string
    required:
      - owner
      - description
```

```diff
$ git diff ../spec/json-schema/EventStreamTable-v0.0.yaml
diff --git a/projects/contract-catalog-integration/spec/json-schema/EventStreamTable-v0.0.yaml b/projects/contract-catalog-integration/spec/json-schema/EventStreamTable-v0.0.yaml
index 2da3700..ab626e6 100644
--- a/projects/contract-catalog-integration/spec/json-schema/EventStreamTable-v0.0.yaml
+++ b/projects/contract-catalog-integration/spec/json-schema/EventStreamTable-v0.0.yaml
@@ -123,7 +123,7 @@ $defs:
       behavior. See
       <https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/tag-resources?tabs=json>.
     type: object
-    additionalProperties: { type: string }
+    additionalProperties: true
     properties:
       owner:
         description: |
```
